# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Forge build workflow

on:
  push:
    branches: [ forge/1.16.3 ]
    paths-ignore:
      - '.github/**'
      - 'curseforge/**'
      - 'versioninfo/**'
      - 'README.md'
      - 'LICENSE.md'
      - 'GRADLE.md'
      - 'changelog.json'
      - '.gitignore'
      - '.gitattributes'
    tags-ignore:
      - '*.*'
  pull_request:
    branches: [ forge/1.16.3 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          architecture: x64

      - name: Permit 'gradlew'
        run: chmod +x gradlew

      - name: Get cached deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Sizzle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 4.10.3
          arguments: build --no-daemon

      - name: Prepare upload
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "Ready to upload the build output to GitHub."

      - name: Upload API
        uses: actions/upload-artifact@v2.2.0
        with:
          name: sizzle-api-${{ env.SHORT_SHA }}
          path: SizzleAPI/build/libs/*.jar
          retention-days: 30

      - name: Upload Client
        uses: actions/upload-artifact@v2.2.0
        with:
          name: sizzle-client-${{ env.SHORT_SHA }}
          path: SizzleMod/build/libs/*client*.jar
          retention-days: 30

      - name: Upload Server
        uses: actions/upload-artifact@v2.2.0
        with:
          name: sizzle-server-${{ env.SHORT_SHA }}
          path: SizzleMod/build/libs/*server*.jar
          retention-days: 30

      - name: Upload Universal
        uses: actions/upload-artifact@v2.2.0
        with:
          name: sizzle-universal-${{ env.SHORT_SHA }}
          path: SizzleMod/build/libs/*universal*.jar
          retention-days: 30
